### ISSUE TITLE
Improve interface detection

### ISSUE THREAD

**Issue by CyrilBrulebois** [PiRogueToolSuite/pirogue-admin#25]
Thanks to a report by the Qurium team, I've been able to confirm a problem regarding interface detection, which shows up when performing the autodetection at install-time, when the `bonding` module is loaded.

This results in the following configuration for a server that meets the current requirements documented in the [Deploy PiRogue VPN cookbook](https://pts-project.org/cookbooks/pirogue-vpn-installation/):
```
DASHBOARD_PASSWORD: 6P0K7be_TKl4wspVX9Y5i5PWRI3DOmdbDXKaj8czzNs6CiEVXIT1nKBVj2x0RkCl
ENABLE_DHCP: true
ENABLE_PUBLIC_ACCESS: false
EXTERNAL_ADDRESS: 37.143.131.172
EXTERNAL_INTERFACE: eth0
EXTERNAL_NETWORKS: 37.143.131.0/24
ISOLATED_ADDRESS: 10.8.0.1
ISOLATED_INTERFACE: bonding_masters
ISOLATED_NETWORK: 10.8.0.0/24
PUBLIC_CONTACT_EMAIL: root@virogue.local
PUBLIC_DOMAIN_NAME: virogue.local
SYSTEM_HOSTNAME: virogue
SYSTEM_OPERATING_MODE: appliance
WIFI_PASSPHRASE: 28d191b3c013f905
```

and the postinst errors out while trying to apply the new configuration:
```
INFO:root:running ['/usr/local/sbin/reconfigure-pirogue-flow-inspector']
Created symlink /etc/systemd/system/default.target.wants/pirogue-flow-inspector@bonding_masters.service → /lib/systemd/system/pirogue-flow-inspector@.service.
Job for pirogue-flow-inspector@bonding_masters.service failed because the control process exited with error code.
See "systemctl status pirogue-flow-inspector@bonding_masters.service" and "journalctl -xeu pirogue-flow-inspector@bonding_masters.service" for details.
Traceback (most recent call last):
  File "/usr/sbin/pirogue-admin", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/pirogue_admin/cmd/cli.py", line 365, in main
    apply_configuration(c_ctx, args.apply)
  File "/usr/lib/python3/dist-packages/pirogue_admin/cmd/cli.py", line 270, in apply_configuration
    loader.apply_configuration(yml_style_config, redeploy)
  File "/usr/lib/python3/dist-packages/pirogue_admin/package_config/__init__.py", line 652, in apply_configuration
    config.apply_configuration(variables)
  File "/usr/lib/python3/dist-packages/pirogue_admin/package_config/__init__.py", line 372, in apply_configuration
    subprocess.check_call(expanded_shell_action_fragments)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/sbin/reconfigure-pirogue-flow-inspector']' returned non-zero exit status 1.
dpkg: error processing package pirogue-base (--configure):
 installed pirogue-base package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 pirogue-base
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The initial code is as follows:
```python
def detect_network_interfaces() -> dict[str, DevType]:
    """
    TODO: Define which interfaces we are comfortable enough to try and
    configure.

    For example, we might want to exclude anything that resembles a virtual
    interface, like a bridge.
    """
    # Start by excluding the loopback:
    interfaces = {}
    for net_dir in sorted(Path('/sys/class/net/').glob('*')):
        if net_dir.name == 'lo':
            continue

        # Unless we know better, an interface is Ethernet-like:
        devtype = DevType.ETHERNET

        # Surely one of wireless flag file vs. DEVTYPE=wlan is enough. And since
        # we might want to exclude things based on DEVTYPE, let's concentrate on
        # that? Otherwise, condition on: (net_dir / 'wireless').exists()
        uevent = net_dir / 'uevent'
        if uevent.exists():
            lines = uevent.read_text().splitlines()

            # KISS: focus on regular interfaces for the time being. We can
            # always try and support bridges when users start asking for it.
            if 'DEVTYPE=bridge' in lines:
                continue

            # The first two we know about and are happy to deal with, other
            # values we flag as unknown:
            if 'DEVTYPE=wlan' in lines:
                devtype = DevType.WIRELESS
            elif 'DEVTYPE=wireguard' in lines:
                devtype = DevType.WIREGUARD
            else:
                for line in lines:
                    if line.startswith('DEVTYPE='):
                        devtype = DevType.UNKNOWN
        interfaces[net_dir.name] = devtype
    return interfaces
```

In our case, `bonding_masters` is actually a regular file, there's of course no `uevent` “below that directory”, so we're sticking to the default `DevType.ETHERNET` and believing that's a reasonable candidate for an isolated interface, hence the issue.

Of course we could just exclude that particular name, but we could have other such entries (auditing the Linux kernel source to build a list would be tedious, and that would likely get out of date anyway).

Therefore I'm proposing to make sure we have a `type` entry in each `net_dir` (which might be a symlink or a directory, likely a symlink to a directory most of the time, but let's not filter on the type, that's likely to be tricky), which is documented the following way (per `Documentation/ABI/testing/sysfs-class-net`):

```
What:           /sys/class/net/<iface>/type
Date:           April 2005
KernelVersion:  2.6.12
Contact:        netdev@vger.kernel.org
Description:
                Indicates the interface protocol type as a decimal value. See
                include/uapi/linux/if_arp.h for all possible values.
```

**Comment by CyrilBrulebois** [comment]
Confirmed fixed with pirogue-admin 2.0.6, closing.
